### ISSUE TITLE
Improve list styling

### ISSUE THREAD

**Issue by sebald** [sebald/spectacle-theme-nova#1]
Using this currently as a drop-in in a presentation. Makes the list look nicer.
Should this be a default?!

```css
ul {
  list-style: none;
}

li {
  position: relative;
  padding-left: 0.875rem !important;
}

li:before {
  content: '-';
  display: block;

  position: absolute;
  left: -12px;

  color: #899ba6;
}
```
